// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://biyrvpqneglyfqcuclvc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJpeXJ2cHFuZWdseWZxY3VjbHZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk3MDA5NzYsImV4cCI6MjA3NTI3Njk3Nn0.KEyIRxF8LfbQknF35WZiy6ZnK8rakYMdhP75D075j2c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);